name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

      # Add your test step here if you have tests
      # - name: Run tests
      #   run: |
      #     pytest

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: 'Export environment variables for Azure Web App'
        run: |
          echo "AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_DEPLOYMENT_NAME=${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME=${{ secrets.AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME }}" >> $GITHUB_ENV
          echo "AZURE_DOCINTELLIGENCE_KEY=${{ secrets.AZURE_DOCINTELLIGENCE_KEY }}" >> $GITHUB_ENV
          echo "AZURE_DOCINTELLIGENCE_ENDPOINT=${{ secrets.AZURE_DOCINTELLIGENCE_ENDPOINT }}" >> $GITHUB_ENV
          echo "BLOB_CONNECTION_STRING=${{ secrets.BLOB_CONNECTION_STRING }}" >> $GITHUB_ENV
          echo "CONTAINER_NAME=${{ secrets.CONTAINER_NAME }}" >> $GITHUB_ENV

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: 'Logout from Azure'
        run: az logout


        
